# Generated by Django 4.1.13 on 2024-02-20 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EGT", "0005_alter_signupcodeemployee_user"),
        ("Notification", "0002_notification_is_deleted_notification_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="enterprise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="EGT.enterprise",
            ),
            preserve_default=False,
        ),
    ]
