# Generated by Django 4.1.13 on 2024-02-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EGT", "0002_alter_enterprise_fund"),
    ]

    operations = [
        migrations.AddField(
            model_name="administratorprofile",
            name="completion_bonus",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
