# Generated by Django 4.1.13 on 2024-02-06 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EGT", "0004_employeeprofile_added_by_signupcodeemployee_added_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupcodeemployee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
