# Generated by Django 4.1.13 on 2024-02-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EGT", "0005_alter_signupcodeemployee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="user_cv"),
        ),
    ]
