# Generated by Django 4.1.13 on 2024-02-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0003_thread_enterprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
