# Generated by Django 4.1.13 on 2024-02-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EGT", "0006_alter_myuser_cv"),
        ("Chat", "0004_alter_thread_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="EGT.enterprise"
            ),
        ),
        migrations.AlterField(
            model_name="threadmessage",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Chat.message"
            ),
        ),
    ]
