# Generated by Django 4.1.13 on 2024-03-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EGT", "0006_alter_myuser_cv"),
        ("Chat", "0007_chat_chatroom_remove_threadmessage_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="enterprise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="EGT.enterprise",
            ),
            preserve_default=False,
        ),
    ]
