# Generated by Django 4.1.13 on 2024-02-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_report_rated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="goal",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
