# Generated by Django 4.1.13 on 2024-02-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_activities_is_sold_goal_is_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="report",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
    ]
