# Generated by Django 4.1.13 on 2024-02-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_activities_is_deleted_goal_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="goal",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
