# Generated by Django 4.1.13 on 2024-02-09 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0005_alter_activities_is_deleted_alter_goal_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="done_employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Enterprise employee's whom finish the activity.",
                related_name="done_employees_set",
                related_query_name="done_employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="done_employees",
            ),
        ),
    ]
