# Generated by Django 4.1.13 on 2024-02-09 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0006_activities_done_employees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activities",
            name="done_employees",
        ),
        migrations.AddField(
            model_name="activities",
            name="submit_employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Enterprise employee's whom submit the activity.",
                related_name="submit_employees_set",
                related_query_name="submit_employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="submit_employees",
            ),
        ),
    ]
