# Generated by Django 4.1.13 on 2024-02-09 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0007_remove_activities_done_employees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="sold_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Enterprise employee's whom submit the activity.",
                related_name="sold_to_set",
                related_query_name="sold_to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="sold_to",
            ),
        ),
    ]
