# Generated by Django 4.1.13 on 2024-02-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_activities_status_alter_goal_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="status",
            field=models.IntegerField(
                choices=[(0, "REJECTED"), (1, "ACCEPTED"), (2, "PENDING"), (3, "PAID")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.IntegerField(
                choices=[(0, "REJECTED"), (1, "ACCEPTED"), (2, "PENDING"), (3, "PAID")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.IntegerField(
                choices=[(0, "REJECTED"), (1, "ACCEPTED"), (2, "PENDING"), (3, "PAID")],
                null=True,
            ),
        ),
    ]
