# Generated by Django 4.1.13 on 2024-02-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_report_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="repetition_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="repetition_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
