# Generated by Django 4.1.13 on 2024-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_report_repeat_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="repeat_option",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "No"), (1, "Daily"), (2, "Weekly"), (3, "Monthly")],
                null=True,
            ),
        ),
    ]
