# Generated by Django 4.1.13 on 2024-02-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_rename_repeat_num_report_repetition_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="repeat_option",
            new_name="repeat",
        ),
    ]
