# Generated by Django 4.1.13 on 2024-02-01 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EGT", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "remaining_bonus",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "remaining_salary",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "transaction_type",
                    models.IntegerField(choices=[(1, "DEPOSIT"), (0, "WITHDRAWAL")]),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "REJECTED"),
                            (1, "ACCEPTED"),
                            (2, "PENDING"),
                            (3, "DONE"),
                        ]
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EGT.enterprise",
                        to_field="name",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
            options={
                "db_table": "Transactions",
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "payment_period",
                    models.IntegerField(
                        choices=[(0, "DAILY"), (1, "WEEKLY"), (2, "MONTHLY")], null=True
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="EGT.enterprise"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
