# Generated by Django 4.1.13 on 2024-02-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="remaining_bonus",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="remaining_salary",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.IntegerField(
                choices=[(0, "REJECTED"), (1, "ACCEPTED"), (2, "PENDING"), (3, "PAID")]
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.IntegerField(
                choices=[(1, "DEPOSIT"), (0, "WITHDRAWAL"), (2, "TRANSFER")]
            ),
        ),
    ]
