# Generated by Django 4.1.13 on 2024-02-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_remove_transaction_remaining_bonus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_deleted",
            field=models.IntegerField(default=False),
        ),
        migrations.DeleteModel(
            name="Payroll",
        ),
    ]
